jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  clouds:
    - mesos:
        agentUser: "${JENKINS_AGENT_USER:-root}"
        frameworkName: "${JENKINS_FRAMEWORK_NAME:-Jenkins Scheduler}"
        jenkinsUrl: "http://jenkins.service.mesos:${PORT0:-8080}"
        mesosAgentSpecTemplates:
          - containerImage: ""
            cpus: "0.1"
            defaultAgent: false
            disk: "0.0"
            executorMem: 128
            idleTerminationMinutes: 3
            jnlpArgs: "-noReconnect"
            jvmArgs: "-Xms16m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true"
            label: "mesos"
            maxExecutors: 1
            mem: 512
            minExecutors: 1
            mode: NORMAL
            remoteFsRoot: "jenkins"
        mesosMasterUrl: "${JENKINS_MESOS_MASTER:-http://leader.mesos:5050}"
        role: "${JENKINS_AGENT_ROLE:-*}"